Off heap combined pr
VermaSh/omr pull request #2
Opened 2024-01-12 21:30 UTC by rmnattas

2024-01-12 22:11 UTC, VermaSh requested changes
Looks good for the most part, just a few minor things.

2024-01-12 22:11 UTC, VermaSh commented on compiler/optimizer/Inliner.cpp
> +      if (( (value->hasPinningArrayPointer()) &&
Can you please remove the extra brace

2024-01-12 22:11 UTC, VermaSh commented on compiler/optimizer/InductionVariable.cpp
> +         //pinningArrayNode->getSymbolReference()->getSymbol()->isAuto() &&
Do we need this commented line?

2024-01-12 22:11 UTC, VermaSh commented on compiler/optimizer/InductionVariable.cpp
> +         //node->recursivelyDecReferenceCount();
Do we need to keep this line around?

2024-01-12 22:11 UTC, VermaSh commented on compiler/optimizer/LoopVersioner.cpp
> +               */
Can you please fix the formatting here.

2024-01-12 22:11 UTC, VermaSh commented on compiler/optimizer/LoopVersioner.cpp
> +         //        so let's reverse the operations on offset to get the index value
Do we need to keep this around?

2024-01-13 16:11 UTC, rmnattas commented
Fixed them 👍

2024-01-15 05:20 UTC, merged